public class Dummy{
private Boolean loadRegion() {
    boolean ret = false;
    String sql = null;
    PreparedStatement stmt = null;
    PreparedStatement ps = null;
    try {
        sql = "CREATE TABLE region (" + " id INTEGER PRIMARY KEY AUTO_INCREMENT," + " country INTEGER	NOT NULL," + " region_name VARCHAR(255)" + ")";
        stmt = this.conn.prepareStatement();
        stmt.execute(sql);
        stmt.close();
        this.conn.setAutoCommit(false);
        sql = "INSERT INTO region(country, region_name) VALUES(?,?)";
        ps = this.conn.prepareStatement(sql);
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Badakhshan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Badghis");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Balkh");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Bamyan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Daykundi");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Farah");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Faryab");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Ghazni");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Ghor");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Helmand");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Herat");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Jowzjan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Kabul");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Kandahar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Kapisa");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Khost");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Kunar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Kunduz");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Laghman");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Logar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Maidan Wardak");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Nangarhar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Nimruz");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Nuristan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Paktia");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Paktika");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Panjshir");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Parwan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Samangan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Sar-e Pol");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Takhar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Urozgan");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='AFG' AND has_division = 1)");
        ps.setObject(2, "Zabul");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Mariehamn");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Jomala");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Finstr�m");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Lemland");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Saltvik");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Hammarland");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Sund");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Ecker�");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "F�gl�");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Br�nd�");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Geta");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "V�rd�");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Lumparland");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Kumlinge");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "K�kar");
        ps.addBatch();
        ps.setObject(1, "(SELECT id FROM country WHERE country_code='ALA' AND has_division = 1)");
        ps.setObject(2, "Sottunga");
        ps.addBatch();
        ps.executeBatch();
        this.conn.commit();
        this.conn.setAutoCommit(true);
        ret = false;
    } catch (Exception ex) {
        System.err.println(ex.toString());
        ret = true;
    } finally {
        try {
            if (!stmt.isClosed())
                stmt.close();
        } catch (Exception ex) {
            System.err.println(ex.toString());
            ret = true;
        }
    }
    return ret;
}}

